[supervisord]
nodaemon=true
user=root

[program:nextjs]
; Next.js standalone server, internal port 3000 per
command=node server.js
directory=/app/frontend
environment=PORT="3000",HOSTNAME="127.0.0.1"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:admin]
command=dotnet /app/admin/AdminPanelProject.dll
environment=ASPNETCORE_URLS="http://127.0.0.1:5002",ASPNETCORE_ENVIRONMENT="Production"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:web]
; Apni actual .dll ka naam check kar lena
command=dotnet /app/web/ktechStore.Web.dll
environment=ASPNETCORE_HTTP_PORTS="%(ENV_PORT)s",ASPNETCORE_ENVIRONMENT="Production"
autostart=true
autorestart=true
priority=999
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0